swapTextureFlag = 0x800E92F8;
swapTexturePointer = 0x1F800044;
clutPointer = 0x1F800028;

enemyDataPointers = 0x80072eac;

title = 0x800d1f28;

loadState = 0x8009811c;
LoadCompressedImage = 0x80017348;
LoadBossRefightsArc = 0x80013524;
LoadBackupScreens = 0x80017668;

ResetGameSettings = 0x8002cf20;

StageLayoutPointers = 0x8007755C;

LevelMidTable = 0x800710f0;
CreateTitleScreenThread = 0x8001e6ac;